config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'items#index'
  resources :items
  resources :orders
  resources :users, only: [:show, :new, :create] do
    resources :carts, only: [:show, :create]
    resources :orders
  end
  resources :cart_items, only: [:new, :create, :destroy]
  resources :charges
  resources :users
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cart.rb
class Cart < ApplicationRecord
  belongs_to :user, required: true
  has_many :cart_items
  has_many :items, through: :cart_items
end

app/models/cart_item.rb
class CartItem < ApplicationRecord
  belongs_to :cart
  belongs_to :item
end

app/models/item.rb
class Item < ApplicationRecord

  validates :title, presence: true, uniqueness: false, length: {in: 3..12 }
  validates :title, presence: true, length: {in: 3..12 }
  validates :description, presence: true, length: {in: 10..200}
  validates :price, numericality: {greater_than: 1}
  has_one_attached :picture
  has_many :carts, through: :cart_items
  has_many :cart_items

  before_create :set_default_picture
end


def set_default_picture
  downloaded_image = (open('https://loremflickr.com/g/320/240/kitten'))
  self.picture.attach(io: downloaded_image, filename: 'image.png')
end

app/models/order.rb
class Order < ApplicationRecord
  after_create :order_email

def order_email
  UserMailer.order_email(self).deliver_now
  AdminMailer.order_email(self).deliver_now
end

end

app/models/user.rb
class User < ApplicationRecord
validates :email, presence: true, uniqueness: true, format: { with: /\A[^@\s]+@([^@\s]+\.)+[^@\s]+\z/, message: "email adress please" }
has_one :cart

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
after_create do
    Cart.create!(user_id: User.last.id)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/cart_items_controller.rb
class CartItemsController < ApplicationController
  before_action :authenticate_user!
  def new
  @cart_item = CartItem.new
end

def create
  @cart = Cart.find_by(user_id: current_user.id)
  @cart_item = CartItem.create(cart_item_params)
    redirect_to user_cart_path(@cart.id,@cart.id)
end

def destroy
  @cart = Cart.find_by(user_id: current_user.id)
  @item = CartItem.where(item_id: params[:id]).first
  @item.destroy
  redirect_to user_cart_path(@cart.id, @cart.id )
end

def cart_item_params
  params.permit(:item_id, :cart_id)
end
end

app/controllers/carts_controller.rb
class CartsController < ApplicationController
  before_action :authenticate_user!
  def show
      @cart_items = CartItem.where(cart_id: params[:id])
      @total = 0.00
      @count = 0
      @cart_items.each do |cart_item|
      @total = cart_item.item.price + @total
      @count += 1
    end
    end
  end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  def index
    @items = Item.all
  end

  def show
    @item = Item.find(params[:id])
  end

  def create
  end

  def new
  end
end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
  before_action :authenticate_user!
  def show
    @orders = Order.where(user_id: current_user.id)
    @list_orders = CartItem.where(cart_id: current_user.id)
  end

  def new
    @order = Order.new
    @cart_items = CartItem.where(cart_id: current_user.id)
    @total = 0.00
    @cart_items.each do |cart_item|
      @total = cart_item.item.price + @total
    end
  end

  def create
    @order = Order.new(cart_id: current_user.id, user_id: current_user.id, stripe_customer_id: params[:stripeToken])
    @total = 0.00
    @cart = CartItem.where(cart_id: current_user.id)
    @cart.each do |cart_item|
      @total = cart_item.item.price + @total
    end

    if @order.save
      puts "ici"
      flash[:success] = "Ta commande est confirmée !"
      @cart_item = CartItem.where(cart_id: current_user.id)
      @cart_item.delete_all
      redirect_to root_path
    else
      flash[:error] = "Ta commande n'a pas pu être confirmée ! Merde alors :("
      render root_path
    end

    customer = Stripe::Customer.create(
      :email => params[:stripeEmail],
      :source  => params[:stripeToken]
    )

    charge = Stripe::Charge.create(
      :customer    => customer.id,
      :amount      => @total.to_i,
      :description => 'Rails Stripe customer',
      :currency    => 'usd'
    )

  rescue Stripe::CardError => e
    flash[:error] = e.message
    redirect_to root_path
  end

  def cart_item_params
    params.permit(:item_id, :cart_id)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  before_action :user_match, only: [:show, :edit, :update]

  def show
    @user = current_user
  end
  def edit
    @user = current_user
  end
  def update
    @user = current_user
    post_params = params.require(:user).permit(:first_name, :last_name, :description)
    @user.update(post_params)
    if @user.update(post_params)

      redirect_to current_user
    else
      render :edit
    end
  end
  def destroy
      @user = User.find(params[:id])
      @user.destroy
      redirect_to admin_user_path
  end
  private
  def user_match
    @user = current_user
    unless current_user.id == @user.id
      redirect_to event_index_path
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def bootstrap_class_for_flash(type)
  case type
    when 'notice' then "alert-info"
    when 'success' then "alert-success"
    when 'error' then "alert-danger"
    when 'alert' then "alert-warning"
  end
end
end

app/helpers/cart_items_helper.rb
module CartItemsHelper
end

app/helpers/carts_helper.rb
module CartsHelper
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/carts/show.html.erb
<link href="//netdna.bootstrapcdn.com/bootstrap/3.0.0/css/bootstrap.min.css" rel="stylesheet" id="bootstrap-css">
<script src="//netdna.bootstrapcdn.com/bootstrap/3.0.0/js/bootstrap.min.js"></script>

<script src="//code.jquery.com/jquery-1.11.1.min.js"></script>
          <div class="container">
              <div class="row">
                  <div class="col-sm-12 col-md-10 col-md-offset-1">
                      <table class="table table-hover">
                          <thead>
                              <tr>
                                  <th>Product</th>
                                  <th> </th>
                                  <th> </th>
                                  <th> </th>
                                  <th> </th>
                                  <th class="text-center">Price</th>
                                  <th class="text-center">Remove</th>
                                  <th> </th>
                              </tr>
                          </thead>


                          <tbody>
                            <% @cart_items.each do |item| %>
                              <tr>
                                  <td class="col-sm-8 col-md-6">
                                  <div class="media">

                                      <a class="thumbnail pull-left" href="#"><%= image_tag  item.item.picture, alt: 'picture', size: "72x72" %> </a>
                                      <div class="media-body"><h4 class="media-heading"><%= item.item.title %></h4></div>
                                  </div>
                                  </td>

                                  <td> </td>
                                  <td> </td>
                                  <td> </td>
                                  <td> </td>
                                  <td class="col-sm-1 col-md-1 text-center"><%= item.item.price %></td>

                                  <td class="text-center"><%= link_to "X", cart_item_path(item.item.id), :method => 'delete', style:"color:red;font-weight:600;"%></td>
                              </tr>
                              <% end %>

                              <tr>
                                  <td>   </td>
                                  <td>   </td>
                                  <td>   </td>
                                  <td>   </td>
                                  <td>   </td>
                                  <td><h3>Total</h3></td>
                                  <td class="text-right"><h3><strong><%= @total %></strong></h3></td>
                              </tr>
                              <tr>
                                  <td>   </td>
                                  <td>   </td>
                                  <td>   </td>
                                  <td>   </td>
                                  <td><button type="button" class="btn btn-default"><%= link_to "Trouver d'autres châtons", root_path, style:"color:black;" %></button></td>
                                  <% if @count > 0 %>
                                  <td><button type="button" class="btn btn-success"><%= link_to "Passer commande", new_user_order_path, style:"color:white;"%></button></td>
                                  <% end %>
                              </tr>
                          </tbody>
                      </table>
                  </div>
              </div>
          </div>

app/views/items/_item.html.erb
<div class="card mb-3 " style="width: 18rem;">
  <h3 class="card-header"><%= item.title %></h3>
  <% if item.picture.attached? ==true %>
  <img class="w-100" display: block" <%= image_tag  item.picture, alt: 'picture' %>
  <% end %>
  <div class="card-body">
    <p class="card-text"><%= item.description %></p>
    <p class="card-text"><%= item.price %></p>
  </div>
  <div class="card-body">
    <a href="#" class="card-link"><a href="/items/<%= item.id %>">Voir le detail</a>
    <% if current_user != nil %>
    <%= link_to "Ajouter au panier", cart_items_path(cart_id: Cart.find_by(user_id: current_user.id), item_id: item.id), class:"card-link", method: :post %>
    <% end %>
  </div>
</div>

app/views/items/create.html.erb
<h1>Items#create</h1>
<p>Find me in app/views/items/create.html.erb</p>

app/views/items/index.html.erb
<!DOCTYPE html>
<html>

<body>
  <center>
  <div class="row">
  <%= render partial: 'item', collection: @items %>
  </div>
  </center>
</body>
</html>

app/views/items/new.html.erb
<h1>Items#new</h1>
<p>Find me in app/views/items/new.html.erb</p>

app/views/items/show.html.erb
<div class="container">
<div class="row">
  <div class="col-5">
    <%=  if @item.picture.attached? ==true
    image_tag @item.picture, width: 300, alt: 'avatar' end  %>
  </div>
  <div class="col-6">
    <br>
    <h2><%= @item.title %></h2>
    <br>
    <h5><%= @item.description %></h5>
    <br>
    <h6>Price : <%= @item.price %></h6>
    <br>

    <% if current_user != nil %>
    <%= link_to "Ajouter au panier", cart_items_path(cart_id: Cart.find_by(user_id: current_user.id), item_id: @item.id), class:"card-link", method: :post %>
    <% end %>
    </div>
</div>

app/views/layouts/_alerts.html.erb
<% flash.each do |type, msg| %>
  <div class="alert <%= bootstrap_class_for_flash(type) %> alert-dismissable fade show" role="alert">
    <%= msg %>
  <button type="button" class="close" data-dismiss="alert" aria-label="Close">
    <span aria-hidden="true">×</span>
  </button>
  </div>
<% end %>

app/views/layouts/_footer.html.erb
<footer class="page-footer font-small special-color-dark pt-4">

    <!-- Footer Elements -->
    <div class="container">

      <!-- Social buttons -->
      <ul class="list-unstyled list-inline text-center">
        <li class="list-inline-item">
          <a class="btn-floating btn-fb mx-1">
            <i class="fab fa-facebook-f"> </i>
          </a>
        </li>
        <li class="list-inline-item">
          <a class="btn-floating btn-tw mx-1">
            <i class="fab fa-twitter"> </i>
          </a>
        </li>
        <li class="list-inline-item">
          <a class="btn-floating btn-gplus mx-1">
            <i class="fab fa-google-plus-g"> </i>
          </a>
        </li>
        <li class="list-inline-item">
          <a class="btn-floating btn-li mx-1">
            <i class="fab fa-linkedin-in"> </i>
          </a>
        </li>
        <li class="list-inline-item">
          <a class="btn-floating btn-dribbble mx-1">
            <i class="fab fa-dribbble"> </i>
          </a>
        </li>
      </ul>
      <!-- Social buttons -->

    </div>
    <!-- Footer Elements -->

    <!-- Copyright -->
    <div class="footer-copyright text-center py-3">© 2018 Copyright:
      <a href="https://mdbootstrap.com/education/bootstrap/"> Trouvetonchat.com</a>
    </div>
    <!-- Copyright -->

  </footer>

app/views/layouts/_head.html.erb
<title>Trouve ton chat</title>
<%= csrf_meta_tags %>
<%= csp_meta_tag %>
<script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.6/umd/popper.min.js" integrity="sha384-wHAiFfRlMFy6i5SRaxvfOCifBUQy1xHdJ/yoi7FRNXMRBu5WHdZYu1hA6ZOblgut" crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.2.1/js/bootstrap.min.js" integrity="sha384-B0UglyR+jN6CkvvICOB2joaf5I4l3gm9GU6Hc1og6Ls7i6U/mkkaduKaBhlAXv9k" crossorigin="anonymous"></script>
<link href="https://stackpath.bootstrapcdn.com/bootstrap/4.2.1/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-GJzZqFGwb1QTTN6wy59ffF1BuGJpLSa9DkKMp0DgiMDm4iYMj70gZWKYbI706tWS" crossorigin="anonymous">
<link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.7.2/css/all.css" integrity="sha384-fnmOCqbTlWIlj8LyTjo7mOUStjsKC4pOpQbqyi7RrhN7udi9RwhKkMHpvLbHG9Sr" crossorigin="anonymous">
<link rel="stylesheet" href="https://bootswatch.com/4/simplex/bootstrap.css" media="screen">
<link rel="stylesheet" href="https://bootswatch.com/_assets/css/custom.min.css">


<%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
<%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <a class="navbar-brand" href="/"><h3><i class="fas fa-cat fa-2x"></i>  Trouve ton chat</h3></a>
  <div class="collapse navbar-collapse" id="navbarNavDropdown">
    <ul class="navbar-nav">
      <li class="nav-item">

      </li>
    </ul>
    </div>
    <% if current_user == nil %>
    <div class="pull-right">
    <div class="dropdown">
      <div class="nav-link dropdown-toggle" href="#" id="navbarDropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
        <i class="fas fa-user fa-2x"></i>
      </div>
      <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdownMenuLink">
       <%= link_to "S'inscrire", new_user_registration_path, class: "dropdown-item" %>
       <%= link_to "Se connecter", new_user_session_path, class: "dropdown-item" %>
      </div>
    </div>
    </div>
    <% else %>
    <div class="nav-item dropdown">
      <div class="nav-link dropdown-toggle" href="#" id="navbarDropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
        <i  class="fas fa-user-secret fa-2x"></i>
      </div>
      <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdownMenuLink">
        <%= link_to "Mon Panier", user_cart_path(user_id: current_user.id, id: Cart.where(user_id: current_user.id).last), class: "dropdown-item" %>
        <%= link_to "Mon Profil", current_user, class: "dropdown-item" %>
        <%= link_to "Déconnexion", destroy_user_session_path, method: :delete, class: "dropdown-item" %>
      </div>
    </div>
    <% end %>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
<%= render 'layouts/head' %>
</head>
<body>
<header>
<%= render 'layouts/navbar' %>
</header>
<!-- Alerts -->
<%= render 'layouts/alerts' %>
<!-- Alerts -->
<%= yield %>
    <!-- Footer -->
<%= render 'layouts/footer' %>
    <!-- Footer -->
</body>
</html>

app/views/layouts/charges.html.erb
<!DOCTYPE html>
<html>
 <head></head>
 <body>
   <%= yield %>
 </body>
</html>

app/views/orders/create.html.erb
<h2>Thanks, you paid <strong>$5.00</strong>!</h2>

app/views/orders/new.html.erb
<%= form_for @order, method: :post do %>
<center>
 <article>
   <% if flash[:error].present? %>
     <div id="error_explanation">
       <p><%= flash[:error] %></p>
     </div>
   <% end %>
   <label class="amount">
     <span>Total : " <%= @total %> "</span>
   </label>
 </article>


 <script src="https://checkout.stripe.com/checkout.js" class="stripe-button"
         data-key="<%= Rails.configuration.stripe[:publishable_key] %>"
         data-description="A month’s subscription"
         data-amount="<%= @total * 100 %>"
         data-locale="auto">
</script>
<% end %>
</center>

app/views/users/edit.html.erb
<html>
  <body>
    <center><h1>Editer mon profil</h1></center>
    <div class="container col-md-8 order-md-1">
    <%= form_for @user do |f| %>
    <div class="form-group">
        <label>Prénom</label>
        <%= f.text_field :first_name, class: "form-control", placeholder: "Jack" %>
        <br />
    </div>
    <div class="form-group">
        <label>Nom</label>
        <%= f.text_field :last_name, class: "form-control", placeholder: "Daniel" %>
        <br />
      </div>
      <div class="form-group">
        <label>Description</label>
        <%= f.text_area :description, class: "form-control", placeholder: "Je raconte ma life..." %>
        <br />
      </div>
      <br />
        <center>
          <br />
        <button type="submit" class="btn btn-primary">Modifier mon profil</button>
        </center>

    <% end %>
    <br />
    <% if @user.errors.any? %>
  <p>Nous n'avons pas réussi à modifier votre compte pour la ou les raisons suivantes :</p>
  <ul>
    <% @user.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
  </ul>
  <% end %>
  </div>

  </body>
</html>

app/views/users/show.html.erb
<div class="jumbotron">
  <h1 class="display-4">Mon profil :<br /><%= @user.first_name %> <%= @user.last_name %></h1>
  <p class="lead"> <h4>Description :</h4><%= @user.description %></p>
  <hr class="my-4">
  <%= link_to "Modifier mon profil", edit_user_path, class:"btn btn-primary" %>
</div>